let favoritePorts=[];try{favoritePorts=JSON.parse(localStorage.getItem('portpulse-favorites')||'[]')}catch(e){favoritePorts=[]}
function isFavorite(name){return favoritePorts.includes(name)}
function toggleFavorite(name){favoritePorts=isFavorite(name)?favoritePorts.filter(x=>x!==name):[...favoritePorts,name];try{localStorage.setItem('portpulse-favorites',JSON.stringify(favoritePorts))}catch(e){}render()}
function favoriteForecast(score){const vals=[score-13,score-8,score-11,score-4,score+3,score+9,score+4,score+14,score+10,score+5,score+1,score-4].map(v=>Math.max(8,Math.min(96,v)));return `<div class="favorite-spark">${vals.map(v=>`<span style="height:${v}%"></span>`).join('')}</div>`}
function favoritePanel(){const active=favoritePorts.map(n=>ports.findIndex(p=>p[0]===n)).filter(i=>i>=0);return `<div class="card favorites-panel"><div class="favorites-head"><div><h2>즐겨찾기 항만</h2><div class="sub">자주 확인하는 항만의 현재 혼잡도와 24시간 예측</div></div><span class="badge green">${active.length}개 저장</span></div>${active.length?`<div class="favorites-grid">${active.map(i=>{const p=ports[i],score=congestionScore(i),tone=congestionTone(score);return `<div class="favorite-card"><div class="favorite-card-top"><div><strong>${p[0]}</strong><small>${congestionStatus(score)} · 평균 대기 ${p[5]}분</small></div><button class="favorite-toggle active" data-favorite="${p[0]}" aria-label="즐겨찾기 해제">★</button></div><div class="favorite-score" style="color:var(--${tone})">${score}<small>/ 100</small></div><div class="favorite-forecast-label"><span>24시간 혼잡도 예측</span><span>현재 → +24h</span></div>${favoriteForecast(score)}</div>`}).join('')}</div>`:'<div class="favorites-empty">항만 화면에서 ★를 눌러 자주 확인하는 항만을 저장해 보세요.</div>'}</div>`}
function addFavoriteButtons(){document.querySelectorAll('.portcard').forEach((card,i)=>{if(card.querySelector('.favorite-toggle'))return;const p=ports[i];if(!p)return;const btn=document.createElement('button');btn.className='favorite-toggle'+(isFavorite(p[0])?' active':'');btn.dataset.favorite=p[0];btn.setAttribute('aria-label',isFavorite(p[0])?'즐겨찾기 해제':'즐겨찾기 추가');btn.textContent=isFavorite(p[0])?'★':'☆';card.querySelector('.port-card-head')?.appendChild(btn);btn.onclick=e=>{e.stopPropagation();toggleFavorite(p[0])}});document.querySelectorAll('.basic-port-card').forEach(card=>{if(card.querySelector('.favorite-toggle'))return;const title=card.querySelector('h2');if(!title)return;const name=title.textContent.trim();const btn=document.createElement('button');btn.className='favorite-toggle'+(isFavorite(name)?' active':'');btn.dataset.favorite=name;btn.setAttribute('aria-label',isFavorite(name)?'즐겨찾기 해제':'즐겨찾기 추가');btn.textContent=isFavorite(name)?'★':'☆';card.querySelector('.basic-port-title')?.appendChild(btn)});document.querySelectorAll('[data-favorite]').forEach(btn=>{if(btn.dataset.boundFavorite)return;btn.dataset.boundFavorite='1';btn.onclick=e=>{e.stopPropagation();toggleFavorite(btn.dataset.favorite)}})}
function renderFavoriteHome(){const page=document.getElementById('page');if(!page||route!=='home')return;const metrics=page.querySelector('.metrics');if(metrics&&!page.querySelector('.favorites-panel'))metrics.insertAdjacentHTML('afterend',favoritePanel())}
const favoriteBaseRender=render;render=function(){favoriteBaseRender();renderFavoriteHome();addFavoriteButtons()};render();

const favoriteObserver=new MutationObserver(()=>addFavoriteButtons());const favoritePage=document.getElementById('page');if(favoritePage)favoriteObserver.observe(favoritePage,{childList:true,subtree:true});
