/* Public weather snapshot generated by GitHub Actions. No API key is exposed in the browser. */
(function () {
  const compass = (deg) => {
    const names = ['북','북동','동','남동','남','남서','서','북서'];
    const n = Number(deg);
    return Number.isFinite(n) ? names[Math.floor(((n + 22.5) % 360) / 45)] : '미상';
  };
  const formatWeather = (w) => {
    if (!w || w.error) return '실시간 기상 확인 중';
    const wind = `${w.windDirection || compass(w.windDirectionDeg)}풍 ${Number(w.windSpeedKn || 0).toFixed(1)}kn`;
    const wave = Number(w.waveHeightM);
    return `${wind} · 파고 ${Number.isFinite(wave) ? wave.toFixed(1) : '-'}m`;
  };
  const apply = (weather) => {
    window.liveWeather = weather;
    const patchPort = (list) => (Array.isArray(list) ? list : []).forEach((p) => {
      const w = weather[p[0]];
      if (w && !w.error) p[8] = formatWeather(w);
    });
    patchPort(typeof ports !== 'undefined' ? ports : []);
    patchPort(typeof tourismPorts !== 'undefined' ? tourismPorts : []);
    patchPort(typeof logisticsPorts !== 'undefined' ? logisticsPorts : []);
    const patchExtra = (list) => (Array.isArray(list) ? list : []).forEach((e) => {
      const w = weather[e[0]];
      if (w && !w.error) e[4] = formatWeather(w);
    });
    patchExtra(typeof portExtras !== 'undefined' ? portExtras : []);
    patchExtra(typeof tourismExtras !== 'undefined' ? tourismExtras : []);
    patchExtra(typeof logisticsExtras !== 'undefined' ? logisticsExtras : []);
    if (typeof render === 'function') render();
    document.documentElement.dataset.liveWeather = 'ready';
  };
  fetch('assets/live-vessel-data.json?weather=' + Date.now(), { cache: 'no-store' })
    .then((r) => r.ok ? r.json() : null)
    .then((data) => { if (data && data.weather) apply(data.weather); })
    .catch(() => {});
})();

const trafficScript = document.createElement('script');
trafficScript.src = 'live-traffic.js?v=1';
document.body.appendChild(trafficScript);
