/* Settings, language and account personalization. Firebase can be enabled later
   by defining window.PORTPULSE_AUTH in the hosting environment. */
(function(){
  const key='portpulse-users', session='portpulse-session';
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch(e){return f}};
  const users=()=>read(key,{}), current=()=>localStorage.getItem(session)||'';
  const saveUsers=(v)=>localStorage.setItem(key,JSON.stringify(v));
  const copy={ko:{title:'설정',lang:'언어',account:'계정',email:'아이디(이메일)',password:'비밀번호',login:'로그인',signup:'계정 만들기',logout:'로그아웃',guest:'게스트 모드',saved:'즐겨찾기 개인화가 이 기기에 저장됩니다.',close:'닫기',en:'English',ko:'한국어'},en:{title:'Settings',lang:'Language',account:'Account',email:'Email',password:'Password',login:'Sign in',signup:'Create account',logout:'Sign out',guest:'Guest mode',saved:'Favorites are saved on this device.',close:'Close',en:'English',ko:'한국어'}};
  let lang=localStorage.getItem('portpulse-lang')||'ko';
  function t(k){return (copy[lang]||copy.ko)[k]||k}
  function syncFavorites(user){if(!user)return;const all=read('portpulse-user-favorites',{});if(all[user]){favoritePorts=all[user];localStorage.setItem('portpulse-favorites',JSON.stringify(favoritePorts))}else all[user]=favoritePorts||[];all[user]=favoritePorts||all[user];localStorage.setItem('portpulse-user-favorites',JSON.stringify(all))}
  function persistFavorites(){const u=current();if(!u)return;const all=read('portpulse-user-favorites',{});all[u]=favoritePorts||[];localStorage.setItem('portpulse-user-favorites',JSON.stringify(all))}
  function modal(){let el=document.getElementById('settings-modal');if(el)return el;el=document.createElement('div');el.id='settings-modal';el.className='settings-backdrop';document.body.appendChild(el);return el}
  function render(){const el=modal(),u=current();el.innerHTML=`<div class="settings-modal" role="dialog" aria-modal="true"><button class="settings-close" aria-label="${t('close')}">×</button><div class="kicker">PORTPULSE AI</div><h2>${t('title')}</h2><section><h3>${t('lang')}</h3><div class="settings-language"><button data-lang="ko" class="${lang==='ko'?'active':''}">${t('ko')}</button><button data-lang="en" class="${lang==='en'?'active':''}">${t('en')}</button></div></section><section><h3>${t('account')}</h3>${u?`<div class="settings-user"><strong>${u}</strong><small>${t('saved')}</small><button class="settings-secondary" data-action="logout">${t('logout')}</button></div>`:`<form id="settings-auth"><input name="email" type="email" placeholder="${t('email')}" required><input name="password" type="password" placeholder="${t('password')}" minlength="6" required><div class="settings-actions"><button class="settings-primary" data-action="login">${t('login')}</button><button class="settings-secondary" data-action="signup">${t('signup')}</button></div><small class="settings-hint">${t('guest')}</small></form>`}</section></div>`;el.hidden=false;el.querySelector('.settings-close').onclick=()=>{el.hidden=true};el.onclick=e=>{if(e.target===el)el.hidden=true};el.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('portpulse-lang',lang);document.documentElement.lang=lang;window.dispatchEvent(new Event('portpulse:language'));if(typeof window.render==='function')window.render();render()});const form=el.querySelector('#settings-auth');if(form){el.querySelector('[data-action="login"]').onclick=e=>{e.preventDefault();auth(form,false)};el.querySelector('[data-action="signup"]').onclick=e=>{e.preventDefault();auth(form,true)}}else el.querySelector('[data-action="logout"]')?.addEventListener('click',()=>{if(window.portpulseFirebaseAuth)window.portpulseFirebaseAuth.signOut();localStorage.removeItem(session);favoritePorts=[];localStorage.setItem('portpulse-favorites','[]');render();if(typeof window.render==='function')window.render()})}
  function auth(form,signup){const fd=new FormData(form),email=String(fd.get('email')||'').trim().toLowerCase(),password=String(fd.get('password')||'');const db=users();if(signup){if(db[email])return alert(lang==='ko'?'이미 등록된 아이디입니다.':'Account already exists.');db[email]={password,createdAt:new Date().toISOString()};saveUsers(db)}else if(!db[email]||db[email].password!==password)return alert(lang==='ko'?'아이디 또는 비밀번호를 확인하세요.':'Invalid email or password.');localStorage.setItem(session,email);syncFavorites(email);render();if(typeof render==='function')render()}
  window.openSettings=render;window.persistAccountFavorites=persistFavorites;
  const oldToggle=window.toggleFavorite; if(typeof oldToggle==='function')window.toggleFavorite=function(n){oldToggle(n);persistFavorites()};
  document.addEventListener('click',e=>{const target=e.target.closest('header>div:last-child');if(target&&/⚙/.test(target.textContent))render()});
  setTimeout(()=>{document.querySelector('header>div:last-child')?.classList.add('settings-trigger')},0);
})();
